### Spring properties
# Service registers under this name
spring:
  application:
    name: stocks-microservicee
    
# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:4321/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 4323
